# Generated by Django 3.0.8 on 2020-10-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0006_usersmodels_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(default=None)),
                ('read', models.BooleanField(default=False)),
                ('notify_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.UsersModels')),
            ],
        ),
    ]
