# Generated by Django 3.0.8 on 2021-01-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(db_index=True, max_length=64)),
                ('author', models.CharField(db_index=True, max_length=64)),
                ('upload_date', models.DateField(auto_now_add=True, db_index=True)),
                ('upload_person', models.CharField(db_index=True, max_length=16)),
                ('series_no', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
