# Generated by Django 3.0.8 on 2021-01-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Model_Book',
        ),
    ]
