# Generated by Django 3.1 on 2021-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20210104_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='upload_person',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.FileField(default=None, upload_to='BookData'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=64),
        ),
    ]
