# Generated by Django 3.1 on 2021-02-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20210224_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to='static/image/pdf_cover'),
        ),
    ]
