# Generated by Django 3.1 on 2021-02-26 07:25

import HelloWorld.Book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20210224_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.FileField(default=None, upload_to=HelloWorld.Book.models.rename_pdf),
        ),
    ]
