# Generated by Django 3.1 on 2021-03-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210316_1724'),
        ('Book', '0008_remove_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload_date',
            field=models.CharField(db_index=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='upload_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_people', to='User.user'),
        ),
    ]
