# Generated by Django 3.1 on 2021-03-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_auto_20210316_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=256),
        ),
    ]
