# Generated by Django 3.2 on 2021-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20210319_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
