# Generated by Django 3.1 on 2021-02-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('slug', models.SlugField(default=None, primary_key=True, serialize=False)),
                ('account', models.CharField(db_index=True, default=None, max_length=64)),
                ('password', models.CharField(default=None, max_length=64)),
                ('birthday', models.DateField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.CharField(default=None, max_length=16)),
            ],
            options={
                'db_table': 'Model_User',
            },
        ),
    ]
