# Generated by Django 3.1 on 2021-02-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210202_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(default=None, upload_to='static/image/static/'),
        ),
    ]
