# Generated by Django 3.1 on 2021-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, default='未命名', max_length=64),
        ),
    ]
