# Generated by Django 3.1 on 2021-02-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1990-01-01', null=True),
        ),
    ]
