# Generated by Django 3.1 on 2021-03-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210220_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
