# Generated by Django 3.0.8 on 2020-09-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodels',
            name='belong_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Users.UsersModels'),
        ),
    ]
