# Generated by Django 3.0.8 on 2020-10-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_usersmodels_slug'),
        ('Tasks', '0002_auto_20200929_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodels',
            name='belong_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Users.UsersModels'),
        ),
        migrations.AlterModelTable(
            name='tasksmodels',
            table='Tasks_tasksmodels',
        ),
    ]
