# Generated by Django 3.0.8 on 2020-09-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModels',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(default=None)),
                ('phone', models.CharField(default=None, max_length=15, primary_key=True, serialize=False)),
                ('undergraduate_college', models.CharField(choices=[('ts', '清华大学'), ('by', '北京邮电大学')], default='none', max_length=10)),
                ('dream_college', models.CharField(max_length=128)),
            ],
        ),
    ]
