# Generated by Django 3.0.8 on 2020-10-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201015_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodels',
            name='username',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
