# Generated by Django 3.0.8 on 2020-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_usersmodels_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodels',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='usersmodels',
            name='user_mask',
            field=models.BinaryField(default=0),
        ),
    ]
