# Generated by Django 3.0.8 on 2020-10-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20201016_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodels',
            name='slug',
            field=models.SlugField(default=None, max_length=64),
        ),
    ]
