# Generated by Django 3.0.8 on 2020-10-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
        ('Users', '0005_usersmodels_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodels',
            name='team',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='Teams.TeamsModels'),
        ),
    ]
