# Generated by Django 3.1 on 2021-06-02 03:41

import HelloWorld.Stock.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0009_user_super_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('slug', models.SlugField(default=None, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default=None, max_length=256)),
                ('cover', models.FileField(default=None, upload_to=HelloWorld.Stock.models.save_cover)),
                ('upgrade_date', models.CharField(db_index=True, default=None, max_length=64)),
                ('public', models.BooleanField(default=False)),
                ('marked_count', models.IntegerField(db_index=True, default=0)),
                ('read_count', models.IntegerField(db_index=True, default=0)),
                ('tag', models.CharField(default='', max_length=64)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='User.user')),
            ],
            options={
                'db_table': 'Model_Stock',
            },
        ),
    ]
